config/routes.rb
RailsBootstrap::Application.routes.draw do
  root :to => 'home#new'

  resources :home do
    collection do
      get :new
      get :about
      get :work
      get :contact
      get :status
      get :talk
      post :mail
    end
  end

  resources :blog

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :verify_authenticity_token  

  def new
  end

  def about
  end

  def work
  end

  def contact
  end

  def status
  end

  def talk
  end

  def mail
    if params["external"]
      ContactMailer.external_mail(params["name"], params["email"], params["message"], params["phone"]).deliver
      render :json => {status: "success"}
    else
      ContactMailer.contact_mail(params["name"], params["email"], params["message"]).deliver
      redirect_to root_path      
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/index.html.erb
<div class="jumbotron">
    <div class="intro-header">

    <div class="intro-header">
    
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Blog</h1>
                        <h3>After the Posterous disaster, now i want to start a blog.</h3>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- /.intro-header -->
  </div>

</div>    

app/views/home/about.html.erb
ABOUT

app/views/home/contact.html.erb
<div class="container">
<div class="row">
<div class="col-sm-4">
<h3>Drop me a line!</h3>
<hr>
<address>
<strong>Email:</strong> <a href="mailto:#"> rozarioed@gmail.com</a><br><br>
<strong>Phone:</strong> 02108453847 <br><br>
<strong>Live@:</strong> Mt.Victoria, Wellington
</address>
</div>
    
<div class="col-sm-8 contact-form">
<form id="mail" method="post" class="form" role="form" action="mail">
<div class="row">
<div class="col-xs-6 col-md-6 form-group">
<input class="form-control" id="name" name="name" placeholder="Name" type="text" required autofocus />
</div>
<div class="col-xs-6 col-md-6 form-group">
<input class="form-control" id="email" name="email" placeholder="Email" type="email" required />
</div>
</div>
<textarea class="form-control" id="message" name="message" placeholder="Message" rows="5"></textarea>
<br />
<div class="row">
<div class="col-xs-12 col-md-12 form-group">
<button class="btn btn-primary pull-right" type="submit">Submit</button>
</form>
</div>
</div>

app/views/home/contact_me.html.erb
<div class="container">
<div class="row">
<div class="col-sm-4">
<h3>Drop me a line!</h3>
<hr>
<address>
<strong>Email:</strong> <a href="mailto:#"> rozarioed@gmail.com</a><br><br>
<strong>Phone:</strong> 02108453847
</address>
</div>
    
<div class="col-sm-8 contact-form">
<form id="mail" method="post" class="form" role="form" action="home#mail">
<div class="row">
<div class="col-xs-6 col-md-6 form-group">
<input class="form-control" id="name" name="name" placeholder="Name" type="text" required autofocus />
</div>
<div class="col-xs-6 col-md-6 form-group">
<input class="form-control" id="email" name="email" placeholder="Email" type="email" required />
</div>
</div>
<textarea class="form-control" id="message" name="message" placeholder="Message" rows="5"></textarea>
<br />
<div class="row">
<div class="col-xs-12 col-md-12 form-group">
<button class="btn btn-primary pull-right" type="submit">Submit</button>
</form>
</div>
</div>

app/views/home/new.html.erb
<script type="text/javascript">
function big_yt(yt_container,url)
{
document.getElementById(yt_container).innerHTML='<div style="position: absolute; left: 50px; top: 100px; right: 50px; bottom: 80px"><div style="position: relative; float: right; cursor: pointer" onclick="document.getElementById(\''+yt_container+'\').innerHTML=\'\'">CLOSE<\/div><br><iframe src="'+url+'" style="position: absolute; width: 100%; height: 100%" frameborder="0"><\/iframe><\/div>'
}
</script>

<script>
$(function(){
  $('#myCarousel').carousel();
});
</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

<div class="right-col">
<div class="pinned note-container">
  <div class="note">
    <i class="fa fa-twitter fa-3x"></i>
    <p><%= TW_CLINET.user_timeline('EdwinARozario', {count: 1, include_rts: true}).first.text %></p>
  </div>
</div>
</div>


<div class="jumbotron">

    <div class="intro-header">

    <div class="intro-header">
    
        <div class="container">

            <div class="row">
                <div class="col-lg-14">
                    <div class="intro-message">
                        <h1>Edwin Rozario</h1>
                        <h3>Programmer, Rocket Enthusiast, Amateur Cook, Part-time Gamer, Dreamer</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li><a href="https://twitter.com/EdwinARozario" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li><a href="https://github.com/EdwinRozario" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li><a href="http://www.linkedin.com/pub/edwin-rozario/46/4a6/742" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li>
                        </ul>
                    </div>
                </div>               
            </div>

        </div>

    </div>
    <!-- /.intro-header -->
  </div>

</div>    


    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Yes I am a Programmer</h2>
                    <p class="lead">
                    Started with C++ at the age of 16, I wasn't serious then. A few kind Geeks and Zed A Shaw helped me
                    understand the basics of programming with Python. "<%= link_to "Learn Python the hard way",  "http://learnpythonthehardway.org/"%>" was so beautiful. Later picked up Ruby and became a full-time Ruby programmer. I have also worked with C# for bread.
                    </p>

                    <p class="lead">
                    So since 2010 i have been actively coding. And i am one lucky guy who usually ends up with good programmers.
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/images/ruby5.jpg" alt="">
                </div>

            </div>

        </div>
        <!-- /.container -->
    </div>
    <!-- /.content-section-a -->



    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Want to build a Rocket
                        <br>Real one</h2>
                    <p class="lead">
                      I dont exactly remember, when did I start fantasizing about Rockets. Normally relectunt to read books, the only books i have read are biographies of <%= link_to "Robert H Goddard",  "http://en.wikipedia.org/wiki/Robert_H._Goddard"%>, <%= link_to "Wernher Von Braun",  "http://en.wikipedia.org/wiki/Wernher_von_Braun"%> and <%= link_to "A P J Abdul Kalam",  "http://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam"%>. Couldnt get a book on <%= link_to "Sergei Korolev",  "http://en.wikipedia.org/wiki/Sergei_Korolev"%>. Have burned mom's kitchen trying to build a rocket engine. The image to the left is of R-7 Semyorka, 60 year old design still going strong. Just like the most efficient class ever written, the basic desing always remain the same but efficient. It seems Korolev had applied <%= link_to "SOLID", "http://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29"%> principles 60 years back in Rocketry. 
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6 col-sm-6">
                    <img class="img-responsive" src="/images/R7.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Eating to Cooking</h2>
                    <p class="lead">
                      Cooking was never my taste untill January 2014. Now i am an amature cook with few tricks up my sleevs. I have tried my dishesh with few of my friends Kiwis, English, Indians and Americans with good results.
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/images/cooking.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->
    </div>

<!-- PUT SOMETHING ABOUT HOUR OF CODE HERE -->
<!--     <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                </div>
                <div class="col-lg-5 col-sm-pull-6 col-sm-6">
                    <img class="img-responsive" src="/images/twitter.gif" alt="">
                </div>
            </div>

        </div>
 -->        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->


    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Tweet-I-Like
                    <p class="lead">
                      Cool image to describe how to design and bulid stuff. I know people who want to build a bicycle, and owns a truck. Prefered using the same truck tyres for the new bicycle. So they wanted to modify the bicycle to include the truck tyres. Finally ended up building the bicycle around the truck tyre. I would never use that bicycle. Seems this tweet explains that. I should had shared this tweet with that designer.
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6 col-sm-6">
                  <blockquote class="twitter-tweet" lang="en"><p>How Spotify builds a product! <a href="https://twitter.com/search?q=%23SoRight&amp;src=hash">#SoRight</a> <a href="http://t.co/rU48jgWe1B">pic.twitter.com/rU48jgWe1B</a></p>&mdash; Siavash Mahmoudian (@siavash) <a href="https://twitter.com/siavash/statuses/457262879733866496">April 18, 2014</a></blockquote>
                <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->


    <div class="banner">

        <div class="container">

            <div class="row">
                <!-- <div class="col-lg-6">
                    <h2>To get in touch:</h2>
                </div> -->
                <div class="col-lg-7">

<!--                     <h4>
                      <%= link_to "My best friend is getting married",  status_home_index_path %>
                    </h4>

                    <ul>
                    <li><%= link_to 'Home', root_path %></span></li>
                    <li><%= link_to 'Work', page_path('about') %></li>
                    <li><%= link_to 'Blog', blog_index_path %></li>
                    <li><%= link_to 'Contact', contact_home_index_path %></li>
                    </ul>
                 <ul class="list-inline banner-social-buttons">
                        <li><a href="https://twitter.com/EdwinARozario" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li><a href="https://github.com/EdwinRozario" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li><a href="http://www.linkedin.com/pub/edwin-rozario/46/4a6/742" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                        <li>
                        <%= link_to "JarviZ".html_safe, 
                        contact_home_index_path, class: "btn btn-primary btn-xl" %>
                        </li>
                    </ul> -->
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#services">Work</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#services">Blog</a>
                        </li>                        
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><%= link_to 'Contact', contact_home_index_path %></li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><%= link_to 'Lets Talk', talk_home_index_path %></li>                        
                        </li>
                    </ul>
                    <!-- <p class="copyright text-muted small">Copyright &copy; Your Company 2013. All Rights Reserved</p> -->
                </div>
            </div>
        </div>
    </footer>

    <!-- Carousel
================================================== -->
<!--    <div id="myCarousel" class="carousel slide" data-ride="carousel">
   
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">

        <div class="item active" style="width: 1500px; height: 700px; margin: 0 auto">
          <%= image_tag('/images/ruby.jpg', size:"1500x700") %>
    
          <div class="container">
            <div class="carousel-caption">
              <h1>Ruby On Rails</h1>
              <p>Currently working with <a href="http://surplustronics.co.nz/">Surplustronics</a>. Incharge of all their web apps and the Ubuntu server.</p>
    
            </div>
          </div>
        </div>
        <div class="item" style="width: 1500px; height: 700px; margin: 0 auto">
          <%= image_tag('/images/csharp.jpg', size:"1500x700") %>

          <div class="container">
            <div class="carousel-caption">
              <h1>Windows MVC</h1>
              <p>Also working with <a href="http://www.grantday.co.nz/">GrantDay Softwares</a>. I am not a big fan of ASP.NET though.</p>

            </div>
          </div>
        </div>
        <div class="item" style="width: 1500px; height: 700px; margin: 0 auto">
          <%= image_tag('/images/marriage.jpg', size:"1500x700") %>

          <div class="container">
            <div class="carousel-caption">
              <h1>My Best friend is getting married.</h1>
              <p>I wish if i could fly down there.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div> -->

app/views/home/status.html.erb
    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
<!--               <hr class="section-heading-spacer"> -->                    

                    <div class="clearfix"></div>
                    <h1 class="section-heading">Arvind is getting married</h1>
                    <p class="lead">
                    <%= link_to "Arvind",  "https://www.facebook.com/arvind.sreenivasan"%> had always been the Mr. Handsome of our group and the one expected to get married anytime. He always had that baby smile and was fun to be around.  
                    </p>

                    <p class="lead">
                    Few months back i received literally the most beautiful email ever, him explaining that he have found his life partner. The email had all the excitement as if Thorin have reclaimed his Gold. 
                    </p>

                    <p class="lead">
                    <h3>I wish you and your beautiful partner (<%= link_to "Priyanka",  "https://www.facebook.com/pinku.mohan.12"%>) a wonderful married life.</h3>
                    </p>                    


                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <br><br>
                    <hr class="section-heading-spacer">
                    <img class="img-responsive" src="/images/arvind.jpg" alt="">
                    <hr class="section-heading-spacer">
                </div>

            </div>

        </div>
        <!-- /.container -->
    </div>


    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">God Delusions
                        <br>by Richard Dawkins</h2>
                    <p class="lead">
                      I become a Rationalist not after seeing <%= link_to "God Delusions",  "http://www.youtube.com/watch?v=9FiHRVb_uE0"%> but i found it after i became rational.
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6 col-sm-6">
                    <img class="img-responsive" src="/images/god-delusions.jpg" alt="">
                </div>
            </div>

        </div>    

app/views/home/talk.html.erb
<div class="jumbotron">

    <div class="intro-header">

    <div class="intro-header">
    
        <div class="container">
            <h2>Lets Talk</h2>
            <div class="row">
				<iframe src="https://appear.in/eddie-your-buddy" width="800" height="640" frameborder="0"></iframe>
            </div>
            <h3>Make sure i am avail...</h3>
        </div>

    </div>
    <!-- /.intro-header -->
  </div>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<!-- <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-center">
        <% render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>
 -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li></li>
<li><%= link_to 'Home', root_path %></span></li>
<li><%= link_to 'Work', page_path('about') %></li>
<li><%= link_to 'Blog', blog_index_path %></li>
<li><%= link_to 'Contact', contact_home_index_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EdwinRozario" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Personal Website" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
        
    <%= yield %>
<!--    <main role="main">
       < render 'layouts/messages' >
       < yield > -->
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

app/views/visitors/new.html.erb
<h3>Home</h3>